version: "3"

services:
  redis:
    image: redis:alpine
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  mongodb:
    image: mvertes/alpine-mongo
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  mqtt:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  api:
    image: printat-api-prod
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
    - NODE_ENV=production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
  web:
    image: printat-web-prod
    ports:
      - "8000:8000"
    depends_on:
      - api
    environment:
    - NODE_ENV=production
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
